name: Run Bot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: npm install
      - name: Run bot
        env:
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME }}
          PIXIAN_API_KEY: ${{ secrets.PIXIAN_API_KEY }}
        run: npm start
